version: "3.9"

services:
  recommendations:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recommendations-service
    ports:
      - "8001:8001"  # Map port 8001 of the container to the host
    volumes:
      - ./chroma_data:/app/chroma_data  # Persist ChromaDB data
    environment:
      - CHROMA_DATA_PATH=/app/chroma_data  # Path for ChromaDB persistence
      - OPENAI_API_KEY=${OPENAI_API_KEY}  # Use your OpenAI API key
    

  
